# Generated by Django 4.1.6 on 2023-04-07 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='flight',
            name='ticket_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ticket Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 23, 42, 42, 471368), verbose_name='Reservation Date'),
        ),
    ]
