# Generated by Django 4.1.6 on 2023-04-07 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_reservation_ticket_price_flight_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='slag',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 23, 53, 50, 130392), verbose_name='Reservation Date'),
        ),
    ]
