# Generated by Django 4.1.6 on 2023-04-07 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_airport_slag_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='slag',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 0, 1, 12, 392926), verbose_name='Reservation Date'),
        ),
    ]
