# Generated by Django 4.1.6 on 2023-04-08 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_airport_slag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 0, 8, 20, 22516), verbose_name='Reservation Date'),
        ),
    ]
